create table if not exists public.menu_items (
  id         bigint generated by default as identity primary key,
  label      text not null,
  href       text not null,
  visible    boolean not null default true,
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.announcement (
  id         integer primary key default 1 check (id = 1),
  enabled    boolean not null default true,
  text       text not null,
  link_label text not null default '',
  link_href  text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.hero (
  id                     integer primary key default 1 check (id = 1),
  eyebrow                text not null,
  heading                text not null,
  paragraph              text not null,
  primary_button_label   text not null,
  primary_button_href    text not null,
  secondary_button_label text not null,
  secondary_button_href  text not null,
  award_title            text not null,
  award_subtitle         text not null,
  image_url              text not null,
  badge_value            text not null,
  badge_label            text not null,
  updated_at             timestamptz not null default now()
);

create table if not exists public.hero_stats (
  id         bigint generated by default as identity primary key,
  value      text not null,
  suffix     text not null default '',
  label      text not null,
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);

do $$
declare
  t text;
begin
  foreach t in array array['menu_items', 'announcement', 'hero', 'hero_stats'] loop
    execute format('alter table public.%I enable row level security', t);

    execute format('drop trigger if exists %I on public.%I', t || '_touch', t);
    execute format('create trigger %I before update on public.%I for each row execute function public.touch_updated_at()', t || '_touch', t);

    execute format('drop policy if exists "Anyone can read" on public.%I', t);
    execute format('create policy "Anyone can read" on public.%I for select to anon, authenticated using (true)', t);

    execute format('drop policy if exists "Admins can add" on public.%I', t);
    execute format('create policy "Admins can add" on public.%I for insert to authenticated with check ((select public.is_admin()))', t);

    execute format('drop policy if exists "Admins can edit" on public.%I', t);
    execute format('create policy "Admins can edit" on public.%I for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()))', t);

    execute format('drop policy if exists "Admins can delete" on public.%I', t);
    execute format('create policy "Admins can delete" on public.%I for delete to authenticated using ((select public.is_admin()))', t);
  end loop;
end $$;

insert into public.menu_items (label, href, sort_order)
select v.label, v.href, v.sort_order
from (values
  ('About', '#about', 1),
  ('AIT', '#ait', 2),
  ('Books & Publications', '#books', 3),
  ('Media', '#media', 4),
  ('Speaking', '#speaking', 5),
  ('Experience', '#experience', 6),
  ('Her Work', '#work', 7)
) as v (label, href, sort_order)
where not exists (select 1 from public.menu_items);

insert into public.announcement (id, enabled, text, link_label, link_href)
values (1, true, 'Recipient of the 2026 AAMFT Clinical Practice Innovation Award —', 'Read more', '#experience')
on conflict (id) do nothing;

insert into public.hero (
  id, eyebrow, heading, paragraph,
  primary_button_label, primary_button_href, secondary_button_label, secondary_button_href,
  award_title, award_subtitle, image_url, badge_value, badge_label
)
values (
  1,
  'Awareness · Integration · Transformation',
  E'Advancing human\nawareness through\n*psychology, education*\n& leadership.',
  'Psychotherapist, educator, author, international speaker and originator of Awareness Integration Theory (AIT). For more than three decades, Dr. Foojan Zeine has helped people move beyond insight — integrating what they know with what they feel, believe, choose and practice.',
  'Explore her work', '#work', 'Speaking & media', '#speaking',
  '2026 AAMFT Clinical Practice Innovation Award',
  'American Association for Marriage and Family Therapy',
  '/images/foojan-hero.png',
  '35+',
  E'years of\nclinical practice'
)
on conflict (id) do nothing;

insert into public.hero_stats (value, suffix, label, sort_order)
select v.value, v.suffix, v.label, v.sort_order
from (values
  ('AIT', '', E'Originator of Awareness\nIntegration Theory', 1),
  ('7', '', E'Books authored\n& co-authored', 2),
  ('25', '', E'Peer-reviewed\narticles', 3),
  ('35', '+', E'Years as a Licensed\nMarriage & Family Therapist', 4),
  ('35', '+', E'Years as a Licensed\nMarriage & Family Therapist', 5)
) as v (value, suffix, label, sort_order)
where not exists (select 1 from public.hero_stats);

drop table if exists public.sections;
