create table if not exists public.speaking (
  id           integer primary key default 1 check (id = 1),
  eyebrow      text not null,
  heading      text not null,
  paragraph    text not null,
  button_label text not null,
  button_href  text not null,
  topics_title text not null,
  updated_at   timestamptz not null default now()
);

create table if not exists public.speaking_formats (
  id         bigint generated by default as identity primary key,
  title      text not null,
  body       text not null,
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.speaking_topics (
  id         bigint generated by default as identity primary key,
  label      text not null,
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);

do $$
declare
  t text;
begin
  foreach t in array array['speaking', 'speaking_formats', 'speaking_topics'] loop
    execute format('alter table public.%I enable row level security', t);

    execute format('drop trigger if exists %I on public.%I', t || '_touch', t);
    execute format('create trigger %I before update on public.%I for each row execute function public.touch_updated_at()', t || '_touch', t);

    execute format('drop policy if exists "Anyone can read" on public.%I', t);
    execute format('create policy "Anyone can read" on public.%I for select to anon, authenticated using (true)', t);

    execute format('drop policy if exists "Admins can add" on public.%I', t);
    execute format('create policy "Admins can add" on public.%I for insert to authenticated with check ((select public.is_admin()))', t);

    execute format('drop policy if exists "Admins can edit" on public.%I', t);
    execute format('create policy "Admins can edit" on public.%I for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()))', t);

    execute format('drop policy if exists "Admins can delete" on public.%I', t);
    execute format('create policy "Admins can delete" on public.%I for delete to authenticated using ((select public.is_admin()))', t);
  end loop;
end $$;

insert into public.speaking (id, eyebrow, heading, paragraph, button_label, button_href, topics_title)
values (
  1,
  'Speaking & Education',
  E'Bringing awareness\n*to the room.*',
  E'Dr. Foojan speaks to professional, academic, leadership and\npublic audiences on psychology, Awareness Integration Theory,\npersonal development, relationships, mental health and\nconscious leadership.',
  'Invite Dr. Foojan to speak',
  '#contact',
  'Signature topics'
)
on conflict (id) do nothing;

insert into public.speaking_formats (title, body, sort_order)
select v.title, v.body, v.sort_order
from (values
  ('Keynotes', 'Conferences & events', 1),
  ('Workshops', 'Professional training', 2),
  ('Academic', 'University lectures', 3)
) as v (title, body, sort_order)
where not exists (select 1 from public.speaking_formats);

insert into public.speaking_topics (label, sort_order)
select v.label, v.sort_order
from (values
  ('Awareness Integration Theory', 1),
  ('Awakened Leadership', 2),
  ('Mental Health & Resilience', 3),
  ('Relationships & Human Behavior', 4),
  ('Intentional Parenting', 5),
  ('AI & Mental Health', 6),
  ('Personal Growth', 7),
  ('Professional Education', 8)
) as v (label, sort_order)
where not exists (select 1 from public.speaking_topics);
