create table if not exists public.footer (
  id             integer primary key default 1 check (id = 1),
  tagline        text not null,
  column_1_title text not null,
  column_2_title text not null,
  column_3_title text not null,
  copyright      text not null,
  address        text not null,
  updated_at     timestamptz not null default now()
);

create table if not exists public.footer_links (
  id         bigint generated by default as identity primary key,
  column_no  integer not null check (column_no between 1 and 3),
  label      text not null,
  href       text not null,
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.footer_socials (
  id         bigint generated by default as identity primary key,
  name       text not null,
  url        text not null,
  icon_url   text not null,
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);

do $$
declare
  t text;
begin
  foreach t in array array['footer', 'footer_links', 'footer_socials'] loop
    execute format('alter table public.%I enable row level security', t);

    execute format('drop trigger if exists %I on public.%I', t || '_touch', t);
    execute format('create trigger %I before update on public.%I for each row execute function public.touch_updated_at()', t || '_touch', t);

    execute format('drop policy if exists "Anyone can read" on public.%I', t);
    execute format('create policy "Anyone can read" on public.%I for select to anon, authenticated using (true)', t);

    execute format('drop policy if exists "Admins can add" on public.%I', t);
    execute format('create policy "Admins can add" on public.%I for insert to authenticated with check ((select public.is_admin()))', t);

    execute format('drop policy if exists "Admins can edit" on public.%I', t);
    execute format('create policy "Admins can edit" on public.%I for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()))', t);

    execute format('drop policy if exists "Admins can delete" on public.%I', t);
    execute format('create policy "Admins can delete" on public.%I for delete to authenticated using ((select public.is_admin()))', t);
  end loop;
end $$;

insert into public.footer (id, tagline, column_1_title, column_2_title, column_3_title, copyright, address)
values (
  1,
  E'Psychotherapist · Author · Educator ·\nInternational Speaker · Originator of Awareness\nIntegration Theory',
  'Explore',
  'Connect',
  'Her Work',
  '© 2026 Dr. Foojan Zeine, Psy.D., LMFT. All rights reserved.',
  '300 S. El Camino Real, Suite 216, San Clemente, CA 92672'
)
on conflict (id) do nothing;

insert into public.footer_links (column_no, label, href, sort_order)
select v.column_no, v.label, v.href, v.sort_order
from (values
  (1, 'About', '#about', 1),
  (1, 'AIT', '#ait', 2),
  (1, 'Books & Publications', '#books', 3),
  (1, 'Experience', '#experience', 4),
  (2, 'Media & Press', '#media', 5),
  (2, 'Speaking', '#speaking', 6),
  (2, 'Contact', '#contact', 7),
  (2, 'Blog', '#', 8),
  (3, 'IAII', '#', 9),
  (3, 'Foojan App', '#', 10),
  (3, 'Mira', '#', 11),
  (3, 'Psychotherapy', '#', 12)
) as v (column_no, label, href, sort_order)
where not exists (select 1 from public.footer_links);

insert into public.footer_socials (name, url, icon_url, sort_order)
select v.name, v.url, v.icon_url, v.sort_order
from (values
  ('LinkedIn', '#', '/images/social/linkedin.svg', 1),
  ('Instagram', '#', '/images/social/instagram.svg', 2),
  ('YouTube', '#', '/images/social/youtube.svg', 3),
  ('Facebook', '#', '/images/social/facebook.svg', 4),
  ('X', '#', '/images/social/x.svg', 5)
) as v (name, url, icon_url, sort_order)
where not exists (select 1 from public.footer_socials);
