create table if not exists public.books_section (
  id           integer primary key default 1 check (id = 1),
  eyebrow      text not null,
  heading      text not null,
  paragraph    text not null,
  footer_text  text not null,
  button_label text not null,
  button_href  text not null,
  updated_at   timestamptz not null default now()
);

create table if not exists public.books (
  id          bigint generated by default as identity primary key,
  category    text not null,
  title       text not null,
  description text not null,
  cover_url   text not null,
  link        text not null default '#',
  sort_order  integer not null default 0,
  updated_at  timestamptz not null default now()
);

do $$
declare
  t text;
begin
  foreach t in array array['books_section', 'books'] loop
    execute format('alter table public.%I enable row level security', t);

    execute format('drop trigger if exists %I on public.%I', t || '_touch', t);
    execute format('create trigger %I before update on public.%I for each row execute function public.touch_updated_at()', t || '_touch', t);

    execute format('drop policy if exists "Anyone can read" on public.%I', t);
    execute format('create policy "Anyone can read" on public.%I for select to anon, authenticated using (true)', t);

    execute format('drop policy if exists "Admins can add" on public.%I', t);
    execute format('create policy "Admins can add" on public.%I for insert to authenticated with check ((select public.is_admin()))', t);

    execute format('drop policy if exists "Admins can edit" on public.%I', t);
    execute format('create policy "Admins can edit" on public.%I for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()))', t);

    execute format('drop policy if exists "Admins can delete" on public.%I', t);
    execute format('create policy "Admins can delete" on public.%I for delete to authenticated using ((select public.is_admin()))', t);
  end loop;
end $$;

insert into public.books_section (id, eyebrow, heading, paragraph, footer_text, button_label, button_href)
values (
  1,
  'Author & researcher',
  E'Ideas developed in|print,\nresearch *&*|*practice.*',
  'From personal transformation and parenting to clinical methodology and leadership.',
  '**7 books** and **25 peer-reviewed articles** across psychology, leadership and personal development.',
  'All books & publications',
  '#'
)
on conflict (id) do nothing;

insert into public.books (category, title, description, cover_url, link, sort_order)
select v.category, v.title, v.description, v.cover_url, v.link, v.sort_order
from (values
  ('Leadership', 'Awakened Leadership', 'Uniting organization development and Awareness Integration Theory.', '/images/book-awakened-leadership.png', '#', 1),
  ('Clinical', 'Awareness Integration Therapy', 'A comprehensive presentation of the AIT therapeutic approach.', '/images/book-ait-therapy.png', '#', 2),
  ('Personal Growth', 'Life Reset', 'The Awareness Integration path to creating the life you want.', '/images/book-life-reset.png', '#', 3),
  ('Parenting', 'Intentional Parenting', 'A practical guide informed by Awareness Integration Theory.', '/images/book-intentional-parenting.png', '#', 4)
) as v (category, title, description, cover_url, link, sort_order)
where not exists (select 1 from public.books);
