create table if not exists public.media_section (
  id                    integer primary key default 1 check (id = 1),
  eyebrow               text not null,
  heading               text not null,
  featured_eyebrow      text not null,
  featured_title        text not null,
  featured_text         text not null,
  featured_button_label text not null,
  featured_button_href  text not null,
  updated_at            timestamptz not null default now()
);

create table if not exists public.media_items (
  id         bigint generated by default as identity primary key,
  kicker     text not null,
  title      text not null,
  body       text not null,
  link       text not null default '#',
  icon_url   text not null,
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);

do $$
declare
  t text;
begin
  foreach t in array array['media_section', 'media_items'] loop
    execute format('alter table public.%I enable row level security', t);

    execute format('drop trigger if exists %I on public.%I', t || '_touch', t);
    execute format('create trigger %I before update on public.%I for each row execute function public.touch_updated_at()', t || '_touch', t);

    execute format('drop policy if exists "Anyone can read" on public.%I', t);
    execute format('create policy "Anyone can read" on public.%I for select to anon, authenticated using (true)', t);

    execute format('drop policy if exists "Admins can add" on public.%I', t);
    execute format('create policy "Admins can add" on public.%I for insert to authenticated with check ((select public.is_admin()))', t);

    execute format('drop policy if exists "Admins can edit" on public.%I', t);
    execute format('create policy "Admins can edit" on public.%I for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()))', t);

    execute format('drop policy if exists "Admins can delete" on public.%I', t);
    execute format('create policy "Admins can delete" on public.%I for delete to authenticated using ((select public.is_admin()))', t);
  end loop;
end $$;

insert into public.media_section (
  id, eyebrow, heading, featured_eyebrow, featured_title, featured_text, featured_button_label, featured_button_href
)
values (
  1,
  'Media & Thought Leadership',
  E'Conversations that|bring\npsychology into|*everyday life.*',
  'Featured show',
  E'Inner Voice — Heartfelt Chat\nwith Dr. Foojan',
  E'Conversations with experts about psychology,\nrelationships, personal growth and what matters most in\nlife.',
  'Watch episodes',
  '#'
)
on conflict (id) do nothing;

insert into public.media_items (kicker, title, body, link, icon_url, sort_order)
select v.kicker, v.title, v.body, v.link, v.icon_url, v.sort_order
from (values
  ('Podcast', 'Expert conversations & interviews', 'Curated appearances and featured discussions.', '#', '/images/media/podcast.svg', 1),
  ('Television & Radio', 'Public psychology & education', 'Selected media appearances and commentary.', '#', '/images/media/tv.svg', 2),
  ('Articles', 'Ideas for a broader audience', E'Psychology, relationships, awareness and personal\ndevelopment.', '#', '/images/media/articles.svg', 3),
  ('Press', 'Media inquiries', 'For producers, journalists and event organizers.', '#contact', '/images/media/press.svg', 4)
) as v (kicker, title, body, link, icon_url, sort_order)
where not exists (select 1 from public.media_items);
