create table if not exists public.experience_section (
  id         integer primary key default 1 check (id = 1),
  eyebrow    text not null,
  heading    text not null,
  paragraph  text not null,
  link_label text not null,
  link_href  text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.experience_tags (
  id         bigint generated by default as identity primary key,
  label      text not null,
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.experience_items (
  id          bigint generated by default as identity primary key,
  kicker      text not null,
  title       text not null,
  body        text not null,
  highlight   boolean not null default false,
  badge_label text not null default '',
  sort_order  integer not null default 0,
  updated_at  timestamptz not null default now()
);

do $$
declare
  t text;
begin
  foreach t in array array['experience_section', 'experience_tags', 'experience_items'] loop
    execute format('alter table public.%I enable row level security', t);

    execute format('drop trigger if exists %I on public.%I', t || '_touch', t);
    execute format('create trigger %I before update on public.%I for each row execute function public.touch_updated_at()', t || '_touch', t);

    execute format('drop policy if exists "Anyone can read" on public.%I', t);
    execute format('create policy "Anyone can read" on public.%I for select to anon, authenticated using (true)', t);

    execute format('drop policy if exists "Admins can add" on public.%I', t);
    execute format('create policy "Admins can add" on public.%I for insert to authenticated with check ((select public.is_admin()))', t);

    execute format('drop policy if exists "Admins can edit" on public.%I', t);
    execute format('create policy "Admins can edit" on public.%I for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()))', t);

    execute format('drop policy if exists "Admins can delete" on public.%I', t);
    execute format('create policy "Admins can delete" on public.%I for delete to authenticated using ((select public.is_admin()))', t);
  end loop;
end $$;

insert into public.experience_section (id, eyebrow, heading, paragraph, link_label, link_href)
values (
  1,
  'Professional Experience',
  E'Experience shaped\nby|*service.*',
  E'More than three decades of clinical practice,\nscholarship, leadership and service across\ndiverse communities.',
  'Full experience & credentials',
  '#'
)
on conflict (id) do nothing;

insert into public.experience_tags (label, sort_order)
select v.label, v.sort_order
from (values ('Clinical Psychology', 1), ('Psychotherapy', 2), ('Education', 3), ('Leadership', 4)) as v (label, sort_order)
where not exists (select 1 from public.experience_tags);

insert into public.experience_items (kicker, title, body, highlight, badge_label, sort_order)
select v.kicker, v.title, v.body, v.highlight, v.badge_label, v.sort_order
from (values
  ('Education & Licensure', 'Clinical psychologist & LMFT',
   'I hold a Doctorate in Clinical Psychology, am a Licensed Marriage and Family Therapist, and earned a Graduate Certificate in Human Behavior from Harvard Extension School. My clinical and scholarly work has included intimate relationships, trauma, anxiety, depression, addictive behaviors, domestic violence, personal development, and integrative mental health.',
   false, '', 1),
  ('Leadership', 'Founder — Personal Growth Institute & My New Life',
   'Earlier in my career, I founded and led the Personal Growth Institute, a nonprofit that delivered multicultural and multilingual mental-health services across five Southern California locations and trained psychotherapy students from 12 universities. I also founded and served as CEO of My New Life, a licensed outpatient chemical-dependency program serving multicultural communities.',
   false, '', 2),
  ('Recognition · 2026', 'AAMFT Clinical Practice Innovation Award',
   'In 2026, I received the American Association for Marriage and Family Therapy Clinical Practice Innovation Award in recognition of innovative clinical practice and the development of Awareness Integration Theory.',
   true, 'Award recipient', 3)
) as v (kicker, title, body, highlight, badge_label, sort_order)
where not exists (select 1 from public.experience_items);
