create table if not exists public.pathways_section (
  id         integer primary key default 1 check (id = 1),
  eyebrow    text not null,
  heading    text not null,
  paragraph  text not null,
  note       text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.pathways (
  id         bigint generated by default as identity primary key,
  title      text not null,
  body       text not null,
  link_label text not null default '',
  href       text not null default '#',
  icon_url   text not null,
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);

do $$
declare
  t text;
begin
  foreach t in array array['pathways_section', 'pathways'] loop
    execute format('alter table public.%I enable row level security', t);

    execute format('drop trigger if exists %I on public.%I', t || '_touch', t);
    execute format('create trigger %I before update on public.%I for each row execute function public.touch_updated_at()', t || '_touch', t);

    execute format('drop policy if exists "Anyone can read" on public.%I', t);
    execute format('create policy "Anyone can read" on public.%I for select to anon, authenticated using (true)', t);

    execute format('drop policy if exists "Admins can add" on public.%I', t);
    execute format('create policy "Admins can add" on public.%I for insert to authenticated with check ((select public.is_admin()))', t);

    execute format('drop policy if exists "Admins can edit" on public.%I', t);
    execute format('create policy "Admins can edit" on public.%I for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()))', t);

    execute format('drop policy if exists "Admins can delete" on public.%I', t);
    execute format('create policy "Admins can delete" on public.%I for delete to authenticated using ((select public.is_admin()))', t);
  end loop;
end $$;

insert into public.pathways_section (id, eyebrow, heading, paragraph, note)
values (
  1,
  'Explore her work',
  E'One body of|work. *Multiple*|\n*pathways.*',
  E'Find the part of Dr. Foojan’s work that speaks to you — whether you are a\nprofessional, a reader, an event organizer or someone seeking support.',
  E'Psychotherapy services, eligibility and current availability are provided through IAII and should be confirmed directly\nthrough Dr. Foojan’s IAII practitioner profile.'
)
on conflict (id) do nothing;

insert into public.pathways (title, body, link_label, href, icon_url, sort_order)
select v.title, v.body, v.link_label, v.href, v.icon_url, v.sort_order
from (values
  ('Awareness Integration Theory',
   'Explore the theory, clinical framework, research foundation and professional applications of AIT.',
   '', '#ait', '/images/pathways/target.svg', 1),
  ('Books & Publications',
   E'Discover Dr. Foojan’s books, peer-reviewed research, articles\nand academic contributions.',
   '', '#books', '/images/pathways/book.svg', 2),
  (E'Speaking &\nEducation',
   E'Keynotes, professional training,\nuniversity education, leadership\nand global presentations.',
   '', '#speaking', '/images/pathways/mic.svg', 3),
  (E'Media &\nConversations',
   E'Podcast, television, radio,\ninterviews and conversations on\npsychology and human\ndevelopment.',
   '', '#media', '/images/pathways/video.svg', 4),
  ('Psychotherapy',
   E'35+ years of clinical practice as an|\nLMFT — relationships, trauma,|\nanxiety, depression, addictive|\nbehaviors and personal|\ndevelopment.',
   'View IAII practitioner profile', '#', '/images/pathways/heart.svg', 5)
) as v (title, body, link_label, href, icon_url, sort_order)
where not exists (select 1 from public.pathways);
