create table if not exists public.ait_section (
  id                     integer primary key default 1 check (id = 1),
  eyebrow                text not null,
  heading                text not null,
  paragraph              text not null,
  primary_button_label   text not null,
  primary_button_href    text not null default '#',
  secondary_button_label text not null,
  secondary_button_href  text not null default '#',
  updated_at             timestamptz not null default now()
);

create table if not exists public.ait_pillars (
  id         bigint generated by default as identity primary key,
  title      text not null,
  body       text not null,
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.ait_tabs (
  id         bigint generated by default as identity primary key,
  title      text not null,
  body       text not null,
  icon_url   text not null,
  tags       text[] not null default '{}',
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);

do $$
declare
  t text;
begin
  foreach t in array array['ait_section', 'ait_pillars', 'ait_tabs'] loop
    execute format('alter table public.%I enable row level security', t);

    execute format('drop trigger if exists %I on public.%I', t || '_touch', t);
    execute format('create trigger %I before update on public.%I for each row execute function public.touch_updated_at()', t || '_touch', t);

    execute format('drop policy if exists "Anyone can read" on public.%I', t);
    execute format('create policy "Anyone can read" on public.%I for select to anon, authenticated using (true)', t);

    execute format('drop policy if exists "Admins can add" on public.%I', t);
    execute format('create policy "Admins can add" on public.%I for insert to authenticated with check ((select public.is_admin()))', t);

    execute format('drop policy if exists "Admins can edit" on public.%I', t);
    execute format('create policy "Admins can edit" on public.%I for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()))', t);

    execute format('drop policy if exists "Admins can delete" on public.%I', t);
    execute format('create policy "Admins can delete" on public.%I for delete to authenticated using ((select public.is_admin()))', t);
  end loop;
end $$;

insert into public.ait_section (id, eyebrow, heading, paragraph, primary_button_label, primary_button_href, secondary_button_label, secondary_button_href)
values (
  1,
  'Signature body of work',
  E'Awareness\nIntegration Theory',
  E'Originated by Dr. Foojan Zeine, AIT is an evidence-informed,\nmultimodality psychological framework that moves people from\ninsight to integration — connecting awareness with beliefs,\nemotions, behaviors, the body, past experiences, identity,\npersonal responsibility and purposeful action.',
  'Explore AIT',
  '#',
  'Research & publications',
  '#books'
)
on conflict (id) do nothing;

insert into public.ait_pillars (title, body, sort_order)
select v.title, v.body, v.sort_order
from (values
  ('Awareness', 'Recognize the patterns, beliefs and past experiences shaping how you think, feel and relate.', 1),
  ('Integration', 'Work through unresolved experiences and align what you know with what you feel and believe.', 2),
  ('Transformation', E'Choose an intentional identity and translate it\ninto purposeful, consistent action.', 3)
) as v (title, body, sort_order)
where not exists (select 1 from public.ait_pillars);

insert into public.ait_tabs (title, body, icon_url, tags, sort_order)
select v.title, v.body, v.icon_url, v.tags, v.sort_order
from (values
  ('Clinical Application',
   E'Psychotherapy and structured personal development — helping\nclients move from understanding their patterns to living\ndifferently.',
   '/images/ait/heart.svg',
   array['Relationships', 'Trauma', 'Anxiety & depression', 'Addictive behaviors', 'Personal development'], 1),
  ('Research',
   'Peer-reviewed studies and ongoing research examining how AIT supports measurable, lasting change across populations.',
   '/images/ait/book.svg',
   array['Peer-reviewed articles', 'Outcome studies', 'Evidence-informed practice'], 2),
  ('Professional Education',
   'Training, certification and continuing education that equip clinicians, coaches and educators to apply AIT.',
   '/images/ait/graduation-cap.svg',
   array['Certification', 'Clinical training', 'University courses', 'Coaching'], 3),
  ('Digital Application',
   'Bringing structured AIT-based reflection and growth tools to people through the Foojan App and the Mira AI companion.',
   '/images/ait/mobile.svg',
   array['Foojan App', 'Mira', 'Guided reflection'], 4)
) as v (title, body, icon_url, tags, sort_order)
where not exists (select 1 from public.ait_tabs);
