create table if not exists public.extending_section (
  id         integer primary key default 1 check (id = 1),
  eyebrow    text not null,
  heading    text not null,
  paragraph  text not null,
  link_label text not null,
  link_href  text not null default '#',
  updated_at timestamptz not null default now()
);

create table if not exists public.extending_cards (
  id         bigint generated by default as identity primary key,
  kicker     text not null,
  title      text not null,
  body       text not null,
  icon_text  text not null default '',
  icon_url   text not null default '',
  links      jsonb not null default '[]',
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);

do $$
declare
  t text;
begin
  foreach t in array array['extending_section', 'extending_cards'] loop
    execute format('alter table public.%I enable row level security', t);

    execute format('drop trigger if exists %I on public.%I', t || '_touch', t);
    execute format('create trigger %I before update on public.%I for each row execute function public.touch_updated_at()', t || '_touch', t);

    execute format('drop policy if exists "Anyone can read" on public.%I', t);
    execute format('create policy "Anyone can read" on public.%I for select to anon, authenticated using (true)', t);

    execute format('drop policy if exists "Admins can add" on public.%I', t);
    execute format('create policy "Admins can add" on public.%I for insert to authenticated with check ((select public.is_admin()))', t);

    execute format('drop policy if exists "Admins can edit" on public.%I', t);
    execute format('create policy "Admins can edit" on public.%I for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()))', t);

    execute format('drop policy if exists "Admins can delete" on public.%I', t);
    execute format('create policy "Admins can delete" on public.%I for delete to authenticated using ((select public.is_admin()))', t);
  end loop;
end $$;

insert into public.extending_section (id, eyebrow, heading, paragraph, link_label, link_href)
values (
  1,
  'Extending the work',
  E'From theory to|institutions,\neducation|*& technology.*',
  'Organizations and products designed to make|AIT accessible to professionals and the|public.',
  'Explore her work in depth',
  '#'
)
on conflict (id) do nothing;

insert into public.extending_cards (kicker, title, body, icon_text, icon_url, links, sort_order)
select v.kicker, v.title, v.body, v.icon_text, v.icon_url, v.links::jsonb, v.sort_order
from (values
  ('Institute',
   'International Awareness Integration Institute',
   'Professional training, certification, therapy, coaching and education built around Awareness Integration Theory.',
   'IAII', '',
   '[{"label": "Explore IAII", "href": "#", "external": false}]', 1),
  ('Mobile App',
   'Foojan App',
   'A digital self-development experience bringing structured AIT-based reflection and growth tools to users.',
   '', '/images/extending/smartphone.svg',
   '[{"label": "App Store", "href": "#", "external": true}, {"label": "Android", "href": "#", "external": true}]', 2),
  ('AI Companion',
   'Mira',
   'An AIT-informed AI companion supporting structured self-reflection, emotional awareness and personal growth within clear ethical boundaries not a replacement for therapy, professional care or human relationship.',
   '', '/images/extending/sparkles.svg',
   '[{"label": "Discover Mira", "href": "#", "external": false}]', 3)
) as v (kicker, title, body, icon_text, icon_url, links, sort_order)
where not exists (select 1 from public.extending_cards);
