create table if not exists public.contact_messages (
  id           bigint generated by default as identity primary key,
  name         text not null check (char_length(name) between 1 and 120),
  email        text not null check (char_length(email) between 3 and 200),
  phone        text not null default '' check (char_length(phone) <= 40),
  organization text not null default '' check (char_length(organization) <= 200),
  inquiry_type text not null check (inquiry_type in ('Speaking', 'Media', 'Education', 'Collaboration', 'Other')),
  message      text not null check (char_length(message) between 10 and 5000),
  is_read      boolean not null default false,
  created_at   timestamptz not null default now()
);

alter table public.contact_messages enable row level security;

drop policy if exists "Anyone can send" on public.contact_messages;
create policy "Anyone can send" on public.contact_messages
  for insert to anon, authenticated with check (is_read = false);

drop policy if exists "Admins can read" on public.contact_messages;
create policy "Admins can read" on public.contact_messages
  for select to authenticated using ((select public.is_admin()));

drop policy if exists "Admins can edit" on public.contact_messages;
create policy "Admins can edit" on public.contact_messages
  for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));

drop policy if exists "Admins can delete" on public.contact_messages;
create policy "Admins can delete" on public.contact_messages
  for delete to authenticated using ((select public.is_admin()));

create table if not exists public.legal_pages (
  slug       text primary key check (slug in ('privacy', 'terms')),
  title      text not null,
  body       text not null,
  updated_at timestamptz not null default now()
);

alter table public.legal_pages enable row level security;

drop trigger if exists legal_pages_touch on public.legal_pages;
create trigger legal_pages_touch before update on public.legal_pages
  for each row execute function public.touch_updated_at();

drop policy if exists "Anyone can read" on public.legal_pages;
create policy "Anyone can read" on public.legal_pages
  for select to anon, authenticated using (true);

drop policy if exists "Admins can add" on public.legal_pages;
create policy "Admins can add" on public.legal_pages
  for insert to authenticated with check ((select public.is_admin()));

drop policy if exists "Admins can edit" on public.legal_pages;
create policy "Admins can edit" on public.legal_pages
  for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));

drop policy if exists "Admins can delete" on public.legal_pages;
create policy "Admins can delete" on public.legal_pages
  for delete to authenticated using ((select public.is_admin()));

insert into public.legal_pages (slug, title, body)
values
  ('privacy', 'Privacy Policy',
   E'## This page is being prepared\nDr. Foojan Zeine''s Privacy Policy will be published here once the final text has been approved.\n\nIf you have a question about how your information is handled, please reach out through the contact page.'),
  ('terms', 'Terms of Use',
   E'## This page is being prepared\nThe Terms of Use for this website will be published here once the final text has been approved.\n\nIf you have a question in the meantime, please reach out through the contact page.')
on conflict (slug) do nothing;

update public.contact_band set primary_button_href = '/contact' where primary_button_href in ('mailto:', '#', '');
update public.speaking set button_href = '/contact' where button_href = '#contact';
update public.media_items set link = '/contact' where link = '#contact';
update public.footer_links set href = '/contact' where label = 'Contact' and href = '#contact';

create table if not exists public.contact_page (
  id           integer primary key default 1 check (id = 1),
  eyebrow      text not null,
  heading      text not null,
  paragraph    text not null,
  office_title text not null,
  office_area  text not null,
  address      text not null,
  map_url      text not null,
  email        text not null,
  phone        text not null,
  updated_at   timestamptz not null default now()
);

alter table public.contact_page enable row level security;

drop trigger if exists contact_page_touch on public.contact_page;
create trigger contact_page_touch before update on public.contact_page
  for each row execute function public.touch_updated_at();

drop policy if exists "Anyone can read" on public.contact_page;
create policy "Anyone can read" on public.contact_page
  for select to anon, authenticated using (true);

drop policy if exists "Admins can add" on public.contact_page;
create policy "Admins can add" on public.contact_page
  for insert to authenticated with check ((select public.is_admin()));

drop policy if exists "Admins can edit" on public.contact_page;
create policy "Admins can edit" on public.contact_page
  for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));

insert into public.contact_page (id, eyebrow, heading, paragraph, office_title, office_area, address, map_url, email, phone)
values (
  1,
  'Get in touch',
  'Speaking, media, education *& collaboration.*',
  'Use this form to invite Dr. Foojan to speak, request an interview, or explore education and collaboration opportunities. Her office will get back to you.',
  'Our office',
  'San Clemente, CA',
  '300 S. El Camino Real, Suite 216, San Clemente, CA 92672',
  'https://goo.gl/maps/bixyQgFJaG4uGSwf6',
  'foojanzeine@gmail.com',
  '+1 (818) 648 2140'
)
on conflict (id) do nothing;
