create table if not exists public.about_page (
  id               integer primary key default 1 check (id = 1),
  eyebrow          text not null,
  heading          text not null,
  subtitle         text not null,
  intro            text not null,
  image_url        text not null,
  body             text not null,
  highlights_title text not null,
  cta_heading      text not null,
  cta_paragraph    text not null,
  cta_button_label text not null,
  cta_button_href  text not null,
  updated_at       timestamptz not null default now()
);

create table if not exists public.about_page_highlights (
  id         bigint generated by default as identity primary key,
  title      text not null,
  items      text not null,
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);

do $$
declare
  t text;
begin
  foreach t in array array['about_page', 'about_page_highlights'] loop
    execute format('alter table public.%I enable row level security', t);

    execute format('drop trigger if exists %I on public.%I', t || '_touch', t);
    execute format('create trigger %I before update on public.%I for each row execute function public.touch_updated_at()', t || '_touch', t);

    execute format('drop policy if exists "Anyone can read" on public.%I', t);
    execute format('create policy "Anyone can read" on public.%I for select to anon, authenticated using (true)', t);

    execute format('drop policy if exists "Admins can add" on public.%I', t);
    execute format('create policy "Admins can add" on public.%I for insert to authenticated with check ((select public.is_admin()))', t);

    execute format('drop policy if exists "Admins can edit" on public.%I', t);
    execute format('create policy "Admins can edit" on public.%I for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()))', t);

    execute format('drop policy if exists "Admins can delete" on public.%I', t);
    execute format('create policy "Admins can delete" on public.%I for delete to authenticated using ((select public.is_admin()))', t);
  end loop;
end $$;

insert into public.about_page (id, eyebrow, heading, subtitle, intro, image_url, body, highlights_title, cta_heading, cta_paragraph, cta_button_label, cta_button_href)
values (
  1,
  E'About Dr. Foojan',
  E'Dr. Foojan Zeine, *Psy.D., LMFT*',
  E'Psychotherapist · Author · Educator · International Speaker · Originator of Awareness Integration Theory',
  E'Dr. Foojan Zeine is an International Speaker, Author, Psychotherapist, and a successful Life and Executive Coach. She has her Doctorate in Clinical Psychology and is a Licensed Marriage & Family Therapist. She has obtained a graduate certificate in the Topic of Human Behavior from the Harvard Extension School (HES).',
  E'/images/foojan-hero.png',
  E'Her expertise is in Intimate Relations and Addictive Behaviors. She has extensive experience treating Depression, Anxiety, Traumas, and Domestic Violence. Foojan presents internationally and is a leading expert in the field of Online Therapy.\n\nShe is the originator and the author of Awareness Integration Theory (AIT), which is a multi-modality Psychology and Educational approach and intervention toward minimizing Depression and Anxiety while improving Self-esteem and Self-confidence. She is the founder of the International Awareness Integration Institute which conducts training workshops to educate and certify psychotherapists, coaches, and teachers in this approach globally. She is the co-developer of the "Foojan" app and the AI companion "Mira" which offers a self-help app offering AIT to the public. She is a lecturer/professor at the California State University Long Beach and Université Paris Cité teaching AIT.\n\n## Books\n\nShe has authored and co-authored many psychology and personal development books. Her latest books included:\n- Awakened Leadership (Routledge, 2025)\n- Intentional Parenting (Cambridge Scholars, 2022)\n- Awareness Integration Therapy – Clear the Past, Create a New Future, and Live a Fulfilled Life Now (Cambridge Scholars, 2021)\n- Life Reset – The Awareness Integration Path to Create the Life You Want (Rowman & Littlefield Publishers, 2017)\n- Online Therapy: A Therapist''s Guide to Expanding Your Practice (W.W. Norton Publishers, 2005)\n- Life Coaching. A chapter in "A Practice That Works: Tips and Strategies for Your Stand-Alone Therapy Practice" (2005)\n\n## Research & editorial work\n\nBesides these books, she published 20 Researched Articles on the Awareness Integration Theory in peer-reviewed journals and is a member of editorial boards and reviews for several esteemed journals, including:\n- INNOSC Theragnostics and Pharmacological Sciences\n- PLOS\n- PLOS Global Public Health\n- Journal of the Neurological Sciences\n- United Scientific Group\n- European Society of Medicine\n\n## Leadership & clinical work\n\nFor over 17 years, Dr. Zeine was the founder and CEO of the Personal Growth Institute, a non-profit organization that provided multicultural and multilingual mental health services across five Southern California locations. PGI served as a training facility for psychotherapy students from 12 universities to complete their licensing hours and qualifications.\n\nDr. Zeine also founded and served as CEO of My New Life, a licensed outpatient chemical dependency facility in Tarzana, California, which catered to the multicultural community recovering from substance and behavioral addictions that was recognized as one of the top 10 recovery programs in Los Angeles County.\n\nIn addition to her clinical roles, Dr. Zeine has an extensive background in hospital administration. She led the Partial Hospital Program Team at Hollywood Community of Van Nuys and Pacifica Hospitals, where she was responsible for organizing, facilitating, and supervising clinical and mental health staff, as well as creating impactful programs for patients. She also developed two Transitional Housing Programs for Battered Women Alternative in Northern California and Haven Hills in Southern California, offering comprehensive case management and counseling services for victims of domestic violence in a residential setting.\n\n## Boards\n\nDr. Zeine serves on the executive and advisory boards of numerous nonprofit organizations, including:\n- Executive Board Member – Iranian American Women''s Foundation\n- Scientific Advisory Board Member – JC''s Recovery & Counseling Center\n- Advisory Board Member – PARS Equality Center\n\n## Media & speaking\n\nDr. Zeine hosts the "Inner Voice – a Heartfelt Chat with Dr. Foojan" podcast and is a sought-after guest speaker at universities such as Harvard, MIT, UCLA, USC, Chicago University, and UC Santa Barbara. She has appeared on the Dr. Phil show on CBS and Fox, and contributed to outlets including YourTango.com, DivorceForce.com, Yoga Journal, Whole Life, Reader''s Digest, Men''s Health, and Huffington Post.',
  E'At a glance',
  E'Invite Dr. Foojan to *speak.*',
  E'For keynotes, professional training, media and collaboration, start a conversation with Dr. Foojan’s office.',
  E'Get in touch',
  E'/contact'
)
on conflict (id) do nothing;

insert into public.about_page_highlights (title, items, sort_order)
select v.title, v.items, v.sort_order
from (values
  (E'Education & licensure', E'Doctorate in Clinical Psychology (Psy.D.)\nLicensed Marriage & Family Therapist (LMFT)\nGraduate certificate in Human Behavior, Harvard Extension School', 1),
  (E'Teaching', E'California State University Long Beach\nUniversité Paris Cité', 2),
  (E'Founder', E'International Awareness Integration Institute\nPersonal Growth Institute\nMy New Life\nCo-developer of the Foojan app and Mira', 3),
  (E'Media & speaking', E'Host of Inner Voice – a Heartfelt Chat with Dr. Foojan\nDr. Phil show on CBS and Fox\nGuest speaker at Harvard, MIT, UCLA, USC and UC Santa Barbara', 4)
) as v (title, items, sort_order)
where not exists (select 1 from public.about_page_highlights);

update public.about set link_href = '/meet-dr-foojan-zeine' where link_href in ('#', '/about');
